### ISSUE TITLE
okc-gpg usage

### ISSUE THREAD

**Issue by 532910** [DDoSolitary/OkcAgent#5] opened 2019-09-29 13:58 UTC
How okc-gpg should be used? Is it just gpg replacement with openkeychain support?

I just got `OkcAgent has stopped` when launch `okc-gpg` in termux shell.

**Comment by 532910** [comment] 2020-06-20 05:54
```
31437 31437 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10092 <<<<<<
31437 31437 D AndroidRuntime: Calling main entry com.example.termuxam.Am
31437 31437 D AndroidRuntime: Shutting down VM
30985 31447 E         : java.lang.Exception: No supported action is found.
30985 31447 E         :         at org.ddosolitary.okcagent.gpg.GpgAgentService.runAgent(GpgAgentService.kt:208)
30985 31447 E         :         at org.ddosolitary.okcagent.AgentService$onStartCommand$1.invoke(AgentService.kt:101)
30985 31447 E         :         at org.ddosolitary.okcagent.AgentService$onStartCommand$1.invoke(AgentService.kt:24)
30985 31447 E         :         at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
30985 31447 E AndroidRuntime: FATAL EXCEPTION: Thread-9
30985 31447 E AndroidRuntime: Process: org.ddosolitary.okcagent, PID: 30985
30985 31447 E AndroidRuntime: java.net.SocketException: Broken pipe
30985 31447 E AndroidRuntime:   at java.net.SocketOutputStream.socketWrite0(Native Method)
30985 31447 E AndroidRuntime:   at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:117)
30985 31447 E AndroidRuntime:   at java.net.SocketOutputStream.write(SocketOutputStream.java:149)
30985 31447 E AndroidRuntime:   at org.ddosolitary.okcagent.gpg.GpgAgentService.runAgent(GpgAgentService.kt:227)
30985 31447 E AndroidRuntime:   at org.ddosolitary.okcagent.AgentService$onStartCommand$1.invoke(AgentService.kt:101)
30985 31447 E AndroidRuntime:   at org.ddosolitary.okcagent.AgentService$onStartCommand$1.invoke(AgentService.kt:24)
30985 31447 E AndroidRuntime:   at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
29285 32533 W ActivityManager:   Force finishing activity org.ddosolitary.okcagent/.MainActivity
29285 29301 I ActivityManager: Showing crash dialog for package org.ddosolitary.okcagent u0
```

**Comment by DDoSolitary** [comment] 2020-07-22 10:10
I haven't wrote the help text so you need to take a look at [`GpgArguments.kt`](https://github.com/DDoSolitary/OkcAgent/blob/master/app/src/main/java/org/ddosolitary/okcagent/gpg/GpgArguments.kt), which lists the supported command line arguments. It is also mentioned in README.md, but the link to the file was broken and I just fixed it.

However, the crash is not expected. It seems that the socket used for communicating with `okc-gpg` is broken after the error message has been sent to it. I'll try to reproduce and fix it.

**Comment by 532910** [comment] 2020-07-22 14:36
Just some update:

```
% okc-agents-r23/okc-gpg
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
zsh: exit 1     okc-agents-r23/okc-gpg
```

OkcAgent from F-Droid crashes the same way:
```
15983 15983 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10092 <<<<<<
15983 15983 D AndroidRuntime: Calling main entry com.example.termuxam.Am
 2414  2488 I ActivityManager: Start proc 15992:org.ddosolitary.okcagent/u0a335 for broadcast org.ddosolitary.okcagent/.GpgProxyReceiver
15992 15992 I Zygote  : seccomp disabled by setenforce 0
15983 15983 D AndroidRuntime: Shutting down VM
15992 16009 I litary.okcagen: Starting a blocking GC Alloc
15992 16009 I litary.okcagen: Starting a blocking GC Alloc
15992 16008 I litary.okcagen: Waiting for a blocking GC Alloc
15992 16009 I litary.okcagen: Alloc concurrent copying GC freed 37453(19MB) AllocSpace objects, 0(0B) LOS objects, 96% free, 1003KB/24MB, paused 529us total 25.482ms
15992 16008 I litary.okcagen: WaitForGcToComplete blocked Alloc on AddRemoveAppImageSpace for 21.724ms
15992 16008 I litary.okcagen: Starting a blocking GC Alloc
15992 16008 E AndroidRuntime: FATAL EXCEPTION: Thread-2
15992 16008 E AndroidRuntime: Process: org.ddosolitary.okcagent, PID: 15992
15992 16008 E AndroidRuntime: java.net.SocketException: Broken pipe
15992 16008 E AndroidRuntime:   at java.net.SocketOutputStream.socketWrite0(Native Method)
15992 16008 E AndroidRuntime:   at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:117)
15992 16008 E AndroidRuntime:   at java.net.SocketOutputStream.write(SocketOutputStream.java:149)
15992 16008 E AndroidRuntime:   at org.ddosolitary.okcagent.GpgAgentService.runAgent(GpgAgentService.kt:223)
15992 16008 E AndroidRuntime:   at org.ddosolitary.okcagent.AgentService$onStartCommand$1.invoke(AgentService.kt:89)
15992 16008 E AndroidRuntime:   at org.ddosolitary.okcagent.AgentService$onStartCommand$1.invoke(AgentService.kt:20)
15992 16008 E AndroidRuntime:   at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
 2414  4440 W ActivityManager: Process org.ddosolitary.okcagent has crashed too many times: killing!
 2414  4440 I ActivityManager: Killing 15992:org.ddosolitary.okcagent/u0a335 (adj 200): crash
 2414  2489 W libprocessgroup: kill(-15992, 9) failed: No such process
 2414  4440 W ActivityManager: Scheduling restart of crashed service org.ddosolitary.okcagent/.GpgAgentService in 1000ms
 2414  2487 I ActivityManager: Showing crash dialog for package org.ddosolitary.okcagent u0
 2414  2489 W libprocessgroup: kill(-15992, 9) failed: No such process
 2414  2489 I libprocessgroup: Successfully killed process cgroup uid 10335 pid 15992 in 45ms
 1956  1956 I Zygote  : Process 15992 exited due to signal (9)
```

**Comment by DDoSolitary** [comment] 2020-07-25 10:27
Fixed empty command line argument incorrectly parsed:
746bb5b22988625f44f39e22b8f28015fce8d4a9
DDoSolitary/okc-agents@743f756e4bb7e54de8d2ad095e86afd762c1f050

Fixed throwing in catch&finally blocks:
0a760f389f2fbc0fbd373cfe7349abc9f8fd6589

**Comment by DDoSolitary** [comment] 2020-07-25 10:28
@532910 Could you please check if okc-gpg gives the correct error message now with the latest dev releases (both okc-gpg and OkcAgent)

**Comment by DDoSolitary** [comment] 2020-07-25 17:01
BTW, even if you passed some invalid options, okc-gpg may seem to hang if stdin is used for input (by not passing a input file name argument). This is because currently OkcAgent tries to read the whole input file before checking the all of the options. It is something I'm going to fix, but for now you can use Ctrl+D to end stdin and then you'll see the error messages.

**Comment by 532910** [comment] 2020-07-26 16:51
> the latest dev releases (both okc-gpg and OkcAgent)

OkcAgent-v0.2.0-45-g766875c.apk + okc-agents-v0.1.0-15-ge0a779b-x86_64.tar.gz

right?

**Comment by DDoSolitary** [comment] 2020-07-26 17:14
App: OkcAgent-v0.2.0-45-g305d980.apk
I force pushed but the original ver got built anyway and I forgot to delete it.

okc-agents: version is correct but you may want the one with -aarch64 suffix if you are going to test it on an ordinary Android phone.

**Comment by 532910** [comment] 2020-07-26 20:52
Now, android app doesn't crash, but okc-gpg gives an error, though another one:

**Comment by 532910** [comment] 2020-07-26 20:59
logcat shows:
```
07-26 23:58:49.489 26840 26840 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10092 <<<<<<
07-26 23:58:49.718 26840 26840 D AndroidRuntime: Calling main entry com.example.termuxam.Am
07-26 23:58:49.795 26840 26840 D AndroidRuntime: Shutting down VM
07-26 23:58:49.859 26655 26849 E GpgAgentService: java.lang.Exception: Invalid option: list-keys
07-26 23:58:49.859 26655 26849 E GpgAgentService: 	at org.ddosolitary.okcagent.gpg.GpgArguments$Companion.errorInvalidOption(GpgArguments.kt:40)
07-26 23:58:49.859 26655 26849 E GpgAgentService: 	at org.ddosolitary.okcagent.gpg.GpgArguments$Companion.parse(GpgArguments.kt:66)
07-26 23:58:49.859 26655 26849 E GpgAgentService: 	at org.ddosolitary.okcagent.gpg.GpgAgentService.runAgent(GpgAgentService.kt:55)
07-26 23:58:49.859 26655 26849 E GpgAgentService: 	at org.ddosolitary.okcagent.AgentService$onStartCommand$1.invoke(AgentService.kt:111)
07-26 23:58:49.859 26655 26849 E GpgAgentService: 	at org.ddosolitary.okcagent.AgentService$onStartCommand$1.invoke(AgentService.kt:23)
07-26 23:58:49.859 26655 26849 E GpgAgentService: 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
07-26 23:58:49.879  2628 14069 I ActivityManager: START u0 {act=org.ddosolitary.okcagent.action.FINISH flg=0x10000000 cmp=org.ddosolitary.okcagent/.IntentRunnerActivity} from uid 10336
07-26 23:58:49.914 26655 26655 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@8d827bc
07-26 23:58:50.020   569   598 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{ee0a5a6 token=Token{c1e6301 ActivityRecord{30fa0e8 u0 org.ddosolitary.okcagent/.IntentRunnerActivity t5372}}}#0
07-26 23:58:50.088  3257  3257 W NotificationEntryMgr: removeNotification for unknown key: 0|android|17040827|null|1000
```

**Comment by 532910** [comment] 2020-07-26 21:08
Trying to use it for pass:

```
07-27 00:07:55.969 29501 29501 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10092 <<<<<<
07-27 00:07:56.195 29501 29501 D AndroidRuntime: Calling main entry com.example.termuxam.Am
07-27 00:07:56.261 29501 29501 D AndroidRuntime: Shutting down VM
07-27 00:07:56.297 26655 29510 E GpgAgentService: java.lang.Exception: Invalid option: quiet
07-27 00:07:56.297 26655 29510 E GpgAgentService: 	at org.ddosolitary.okcagent.gpg.GpgArguments$Companion.errorInvalidOption(GpgArguments.kt:40)
07-27 00:07:56.297 26655 29510 E GpgAgentService: 	at org.ddosolitary.okcagent.gpg.GpgArguments$Companion.parse(GpgArguments.kt:66)
07-27 00:07:56.297 26655 29510 E GpgAgentService: 	at org.ddosolitary.okcagent.gpg.GpgAgentService.runAgent(GpgAgentService.kt:55)
07-27 00:07:56.297 26655 29510 E GpgAgentService: 	at org.ddosolitary.okcagent.AgentService$onStartCommand$1.invoke(AgentService.kt:111)
07-27 00:07:56.297 26655 29510 E GpgAgentService: 	at org.ddosolitary.okcagent.AgentService$onStartCommand$1.invoke(AgentService.kt:23)
07-27 00:07:56.297 26655 29510 E GpgAgentService: 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
07-27 00:07:56.310  2628 14069 I ActivityManager: START u0 {act=org.ddosolitary.okcagent.action.FINISH flg=0x10000000 cmp=org.ddosolitary.okcagent/.IntentRunnerActivity} from uid 10336
```

**Comment by DDoSolitary** [comment] 2020-07-27 02:27
Well, this is simply because these options are not supported.

- `--list-keys` can not be supported because OpenKeychain doesn't provide API for this.
- `--quiet` is possible to support.

**Comment by 532910** [comment] 2020-07-28 01:15
Unfortunately it's still impossible to use okc-gpg for pass, not it says: `Invalid option: yes`

**Comment by DDoSolitary** [comment] 2020-07-28 04:58
I just took a look at the source code of pass and it seems that there's a lot more work to do to be compatible with it.

**Comment by DDoSolitary** [comment] 2020-07-28 05:45
Some options that's used by pass but can't be supported:

- `--list-keys`: OpenKeychain doesn't allow retrieving all public keys, it also only provides key ids but not fingerprints
- `--decrypt --list-only`: OpenKeychain doesn't provide information about the public key used to encrypt a message
- `--verify --status-fd=1`: pass parses the output to get fingerprints but again OpenKeychain doesn't provide fingerprints.

**Comment by DDoSolitary** [comment] 2020-07-28 06:11
Basic operations including `insert`ing and reading passwords should work now.

**Comment by 532910** [comment] 2020-07-28 15:54
awesome!

**Comment by DDoSolitary** [comment] 2020-08-02 15:02
I will close it for now because it is generally impossible to support the aforementioned options without changes on the OpenKeychain's side.

**Closed by DDoSolitary** 2020-08-02 15:02 UTC
